// This file is generated by scripts/generate-config-from-typebox.ts.
// Do not edit this file by hand.

export interface ServerZGeneratedConfig {
    meta: {
        /**
         * The Steam App ID for DayZ Server
         * @default 223350
         * @env APP_ID
         */
        appID: number
        /**
         * The path to the DayZ server binary
         * @default "DayZServer"
         * @env DAYZ_BINARY_PATH
         */
        dayZBinaryPath: string
        /**
         * The directory where the server is installed. This should be bind-mounted to a persistent directory on the host.
         * @default "/install/"
         * @env INSTALL_DIRECTORY
         */
        installDirectory: string
        /**
         * The directory in the container where the overlay filesystem is mounted. This is the merged view of `INSTALL_DIRECTORY`, `OVERRIDES_DIRECTORY`, `GENERATED_CONFIG_DIRECTORY`, and `DATA_DIRECTORY`.
         * @default "/dayz/"
         * @env SERVER_DIRECTORY
         */
        serverDirectory: string
        /**
         * The directory to override files in `INSTALL_DIRECTORY` with. This directory should be bind-mounted to the host.
         * @default "/overrides/"
         * @env OVERRIDES_DIRECTORY
         */
        overridesDirectory: string
        /**
         * The directory where OverlayFS stores its scratch space. Must be on the same filesystem as `DATA_DIRECTORY` (the upperdir).
         * @default ".overlay-work"
         * @env OVERLAY_FS_SCRATCH_DIRECTORY
         */
        overlayFSScratchDirectory: string
        /**
         * The directory where ServerZ stores configuration files it generated. This directory should not be bind-mounted to the host, ServerZ generates these files on startup.
         * @default "/tmp/serverz/dayz/"
         * @env GENERATED_CONFIG_DIRECTORY
         */
        generatedConfigDirectory: string
        /**
         * The directory where DayZ writes are stored. This directory should be bind-mounted to the host.
         * @default "/data/"
         * @env DATA_DIRECTORY
         */
        dataDirectory: string
        /**
         * The (game) port the server will run on
         * @default 2302
         * @env PORT
         */
        port: number
        /**
         * The path to the profiles directory. If kept at the default location, this directory does not need to be bind-mounted to the host.
         * @default "profiles"
         * @env PROFILES_PATH
         */
        profilesPath: string
        /**
         * An array of player's SteamID64s to give queue priority to. Example: `'["01234567890123456", "01234567890123456"]'`
         * @default []
         * @env PRIORITY
         */
        priority: string[]
        /**
         * The path to the server configuration file, to be given to DayZServer. Changing this will result in all **Server** environment variables being ignored.
         * @default "serverDZ.generated.cfg"
         * @env CONFIG_PATH
         */
        configPath: string
        /**
         * The number of CPU cores for DayZServer to use.
         * @env CPU_COUNT
         */
        cpuCount: number
        /**
         * adds -dologs to the server start command
         * @env DO_LOGS
         */
        doLogs: boolean
        /**
         * adds -adminlog to the server start command
         * @env ADMIN_LOG
         */
        adminLog: boolean
        /**
         * adds -netlog to the server start command
         * @env NET_LOG
         */
        netLog: boolean
        /**
         * adds -freezecheck to the server start command
         * @env FREEZE_CHECK
         */
        freezeCheck: boolean
        /**
         * The path to the BattlEye directory
         * @default "battleye"
         * @env BE_PATH
         */
        bePath: string
        /**
         * AN array of mod IDs to download and enable on the server
         * @default []
         * @env MOD_LIST
         */
        modList: number[]
        /**
         * The Steam App ID the workshop items (AKA: the mods) are associated with
         * @default 221100
         * @env MOD_APP_ID
         */
        modAppID: number
        /**
         * The container path to where the downloaded workshop items can be found
         * @default "steamapps/workshop/content"
         * @env MOD_PATH
         */
        modPath: string
        /**
         * On start, the server will uninstall and delete all mods not found in `MOD_LIST`. (Uninstallation is limited to reversing any actions performed by the server to install the mods, any other configuration (whether applied manually or by the mod itself) will remain)
         * @env CLEAN_MODS
         */
        cleanMods: boolean
        /**
         * Any additional arguments to pass to the server start command
         * @env EXTRA_STARTUP_ARGS
         */
        extraStartupArgs?: string
        /**
         * Skips the server update process
         * @env SKIP_UPDATE
         */
        skipUpdate: boolean
        /**
         * Skips the mod update process
         * @env SKIP_MOD_UPDATE
         */
        skipMods: boolean
        /**
         * Skips the map update process
         * @env SKIP_MAP_UPDATE
         */
        skipMap: boolean
        /**
         * Starts DayZServer. Set to false if, for example, you only want to update the server and mods.
         * @default true
         * @env START_DAYZ_SERVER
         */
        startDayZServer: boolean
        /**
         * The URL to download the map from. If set, ServerZ will download the map from the URL and symlink it into `MAPS_PATH`.
         * @env MAP_URL
         */
        mapURL?: string
        /**
         * **Deprecated.** When set to true, will copy the mission directory into `mpmissions`. This option is deprecated and will be removed in a future version. OverlayFS ensures all mission edits persist automatically. COPY_MISSION was a workaround for persistence that should no longer be needed. If OverlayFS doesn't replace this option for you, please let us know by creating an issue. See [readme.md#issues](../readme.md#issues)
         * @env COPY_MISSION
         * @deprecated
         */
        copyMission?: boolean
        /**
         * When `COPY_MISSION` is enabled, copy the mission into `OVERRIDES_DIRECTORY/mpmissions` instead of `INSTALL_DIRECTORY/mpmissions`. Useful when mission files should live with operator-managed overrides.
         * @env COPY_MISSION_UP
         */
        copyMissionUp?: boolean
        /**
         * The container path to download maps to.
         * @default "maps"
         * @env MAPS_PATH
         */
        mapsPath: string
        /**
         * The container path to the mission directory to symlink into `mpmissions`. For custom maps this would usually be `/dayz/maps/<mission>` and would not be a directory within the `mpmissions` directory.
         * @default "mpmissions/dayzOffline.chernarusplus"
         * @env MISSION_PATH
         */
        missionPath: string
        /**
         * When set to true, will overwrite any existing map when the server starts. Warning: this may cause data loss.
         * @env UPDATE_MAP
         */
        updateMap: boolean
        /**
         * When **not set to false**, the server will exit when the child process (DayZServer) exits.
         * @default true
         * @env EXIT_WITH_CHILD
         */
        exitWithChild: boolean
        /**
         * How long to wait after forwarding SIGTERM/SIGINT to DayZServer before resorting to SIGKILL.
         * @default 60000
         * @env SHUTDOWN_TIMEOUT_MS
         */
        shutdownTimeoutMs: number
        /**
         * **Enable overlay behavior.** When `true`, the server directory (`SERVER_DIRECTORY`, usually `/dayz`) is built as an overlay of the base install (`INSTALL_DIRECTORY`) plus operator overrides (`OVERRIDES_DIRECTORY`). Writes by the DayZ server are captured to `DATA_DIRECTORY`. When `false`, the system falls back to _copy mode_: all files are copied from base + overrides into the server directory on startup. Writes by the server may not persist across restarts.
         * @default true
         * @env USE_OVERLAYFS
         */
        useOverlayFS: boolean
        /**
         * **Choose overlay backend.** When `undefined`, ServerZ tries kernel OverlayFS first, then falls back to `fuse-overlayfs` if kernel mount fails. When `true`, ServerZ skips the kernel attempt and uses `fuse-overlayfs` directly (useful in rootless Docker/Podman). When `false`, ServerZ uses kernel OverlayFS only; if that fails, it falls back to copy mode instead of fuse.
         * @env USE_FUSE
         */
        useFuse?: boolean
        /**
         * Use user xattrs for overlayfs. You probably don't need to change this.
         * @env USE_USERXATTR
         */
        userXAttr?: boolean
        /**
         * Wipe persistent server data before continuing startup. Set to `true` to perform the wipe, or `dry-run` to log what would be removed without deleting anything. After the wipe, the server will hang pending your intervention to unset this option and restart.
         * @env WIPE
         */
        wipe?: boolean | "dry-run"
        /**
         * Also wipe `INSTALL_DIRECTORY` when `WIPE` is enabled. By default, wipes target persistent data and profiles without deleting the installed server files.
         * @env WIPE_INSTALL
         */
        wipeInstall: boolean
        /**
         * Timeout (in seconds) for the wipe process. It's discouraged to set this lower than the default.
         * @default 30
         * @env WIPE_TIMEOUT
         */
        wipeTimeout: number
        /**
         * Character IDs allowed to connect when whitelist is enabled.
         * @default []
         * @env WHITELIST
         */
        whitelist: string[]
        /**
         * list of SteamID64s banned from connecting when banlist is enabled.
         * @default []
         * @env BANLIST
         */
        banned: string[]
    }
    server: {
        /**
         * The server name.
         * @default "Example Server"
         * @env SERVER_NAME
         */
        serverName: string
        /**
         * The server description.
         * @env DESCRIPTION
         */
        description: string
        /**
         * The server password.
         * @env PASSWORD
         */
        password?: string
        /**
         * ENABLE_WHITELIST is set to `true` by default when `WHITELIST` is set. Set to `false` to explicitly disable it without needing to remove the whitelist.
         * @env ENABLE_WHITELIST
         */
        enableWhitelist?: boolean
        /**
         * Disables the banlist.
         * @env DISABLE_BANLIST
         */
        disableBanlist: boolean
        /**
         * Disables the prioritylist.
         * @env DISABLE_PRIORITYLIST
         */
        disablePrioritylist: boolean
        /**
         * The admin password.
         * @env ADMIN_PASSWORD
         */
        adminPassword?: string
        /**
         * The maximum number of players allowed on the server.
         * @default 60
         * @env MAX_PLAYERS
         */
        maxPlayers: number
        /**
         * Verifies .pbos against .bisign files. (only 2 is supported)
         * @default 2
         * @env VERIFY_SIGNATURES
         */
        verifySignatures: number
        /**
         * When enabled, the server only allows clients with the same .exe revision as the server.
         * @default true
         * @env FORCE_SAME_BUILD
         */
        forceSameBuild: boolean
        /**
         * Disables VoN (Voice over Net) support.
         * @env DISABLE_VON
         */
        disableVon: boolean
        /**
         * Voice over network codec quality, the higher the better (values 0-20)
         * @default 20
         * @env VON_CODEC_QUALITY
         */
        vonCodecQuality: number
        /**
         * Disables third-person view for players.
         * @env DISABLE_3RD_PERSON
         */
        disable3rdPerson: boolean
        /**
         * Disables the cross-hair.
         * @default true
         * @env DISABLE_CROSSHAIR
         */
        disableCrosshair: boolean
        /**
         * Initial in-game time of the server. "SystemTime" means the local time of the machine. Another possibility is to set the time to some value in "YYYY/MM/DD/HH/MM" format, e.g "2015/4/8/17/23".
         * @default "SystemTime"
         * @env SERVER_TIME
         */
        serverTime: string
        /**
         * Accelerated Time - The numerical value being a multiplier (0.1-64). Thus, in case it is set to 24, time would move 24 times faster than normal. An entire day would pass in one hour.
         * @default 1
         * @env SERVER_TIME_ACCELERATION
         */
        serverTimeAcceleration: number
        /**
         * Accelerated Nigh Time - The numerical value being a multiplier (0.1-64) and also multiplied by serverTimeAcceleration value. Thus, in case it is set to 4 and serverTimeAcceleration is set to 2, night time would move 8 times faster than normal. An entire night would pass in 3 hours.
         * @default 1
         * @env SERVER_NIGHT_TIME_ACCELERATION
         */
        serverNightTimeAcceleration: number
        /**
         * When enabled, the actual server time is saved to storage and reused on the next server start.
         * @env SERVER_TIME_PERSISTENT
         */
        serverTimePersistent: boolean
        /**
         * Communication protocol used with game server (use only number 1)
         * @default 1
         * @env GUARANTEED_UPDATES
         */
        guaranteedUpdates: number
        /**
         * The number of players concurrently processed during the login process. Should prevent massive performance drop during connection when a lot of people are connecting at the same time.
         * @default 5
         * @env LOGIN_QUEUE_CONCURRENT_PLAYERS
         */
        loginQueueConcurrentPlayers: number
        /**
         * The maximum number of players that can wait in login queue.
         * @default 500
         * @env LOGIN_QUEUE_MAX_PLAYERS
         */
        loginQueueMaxPlayers: number
        /**
         * DayZ server instance id, to identify the number of instances per box and their storage folders with persistence files.
         * @default 1
         * @env INSTANCE_ID
         */
        instanceID: number
        /**
         * When enabled, corrupted persistence files are replaced with empty ones.
         * @default true
         * @env STORAGE_AUTO_FIX
         */
        storageAutoFix: boolean
        /**
         * Sets the respawn delay (in seconds) before the player is able to get a new character on the server, when the previous one is dead
         * @env RESPAWN_TIME
         */
        respawnTime?: number
        /**
         * Message of the day displayed in the in-game chat
         * @default ["DayZ in a Box!"]
         * @env MOTD
         */
        motd: string[]
        /**
         * Time interval (in seconds) between each message
         * @default 300
         * @env MOTD_INTERVAL
         */
        motdInterval: number
        /**
         * Format for timestamps in the .rpt file (value Full/Short)
         * @env TIMESTAMP_FORMAT
         */
        timestampFormat?: string
        /**
         * Logs the average server FPS (value in seconds), needs to have the DO_LOGS environment variable set
         * @env LOG_AVERAGE_FPS
         */
        logAverageFPS?: number
        /**
         * Logs the server memory usage (value in seconds), needs to have the the DO_LOGS environment variable set
         * @env LOG_MEMORY
         */
        logMemory?: number
        /**
         * Logs the count of currently connected players (value in seconds), needs to have the the DO_LOGS environment variable set
         * @env LOG_PLAYERS
         */
        logPlayers?: number
        /**
         * Saves the server console log to a file in the folder with the other server logs
         * @env LOG_FILE
         */
        logFile?: string
        /**
         * When enabled, logs player hits only; when disabled, logs all hits, including animals and infected.
         * @env ADMIN_LOG_PLAYER_HITS_ONLY
         */
        adminLogPlayerHitsOnly?: boolean
        /**
         * When enabled, logs placement actions, such as traps and tents.
         * @env ADMIN_LOG_PLACEMENT
         */
        adminLogPlacement?: boolean
        /**
         * When enabled, logs base-building actions, such as build, dismantle, and destroy.
         * @env ADMIN_LOG_BUILD_ACTIONS
         */
        adminLogBuildActions?: boolean
        /**
         * When enabled, logs the periodic player list with positions every 5 minutes.
         * @env ADMIN_LOG_PLAYER_LIST
         */
        adminLogPlayerList?: boolean
        /**
         * Disables multi-account mitigation.
         * @env DISABLE_MULTI_ACCOUNT_MITIGATION
         */
        disableMultiAccountMitigation?: boolean
        /**
         * Shows character information using a debug window in a corner of the screen.
         * @env ENABLE_DEBUG_MONITOR
         */
        enableDebugMonitor?: boolean
        /**
         * defines Steam query port, should fix the issue with server not being visible in client server browser. (ServerZ Note: The default has been changed to what steam expects, and differs from Bohemia's default of 2305)
         * @default 27015
         * @env STEAM_QUERY_PORT
         */
        steamQueryPort: number
        /**
         * Enables connections from clients using the "-filePatching" launch parameter.
         * @env ALLOW_FILE_PATCHING
         */
        allowFilePatching?: boolean
        /**
         * Set limit of how much players can be simulated per frame (for server performance gain)
         * @env SIMULATED_PLAYERS_BATCH
         */
        simulatedPlayersBatch?: number
        /**
         * Enables multi-threaded processing of the server's replication system. Number of worker threads is derived by settings of jobsystem in dayzSettings.xml by "maxcores" and "reservedcores" parameters.
         * @env MULTITHREADED_REPLICATION
         */
        multithreadedReplication?: boolean
        /**
         * enable speedhack detection, values 1-10 (1 strict, 10 benevolent, can be float)
         * @env SPEEDHACK_DETECTION
         */
        speedhackDetection?: number
        /**
         * network bubble distance for spawn of close objects with items in them (f.i. backpacks), set in meters, default value if not set is 20
         * @env NETWORK_RANGE_CLOSE
         */
        networkRangeClose?: number
        /**
         * network bubble distance for spawn (despawn +10%) of near inventory items objects, set in meters, default value if not set is 150
         * @env NETWORK_RANGE_NEAR
         */
        networkRangeNear?: number
        /**
         * network bubble distance for spawn (despawn +10%) of far objects (other than inventory items), set in meters, default value if not set is 1000
         * @env NETWORK_RANGE_FAR
         */
        networkRangeFar?: number
        /**
         * network bubble distance for spawn of effects (currently only sound effects), set in meters, default value if not set is 4000
         * @env NETWORK_RANGE_DISTANT_EFFECT
         */
        networkRangeDistantEffect?: number
        /**
         * Maximum time a bubble can take to iterate in seconds before it is logged to the console
         * @env NETWORK_OBJECT_BATCH_LOG_SLOW
         */
        networkObjectBatchLogSlow?: number
        /**
         * Enables a limiter for object creation based on bandwidth statistics.
         * @env NETWORK_OBJECT_BATCH_ENFORCE_BANDWIDTH_LIMITS
         */
        networkObjectBatchEnforceBandwidthLimits?: boolean
        /**
         * When disabled, bandwidth usage is based on actual data sent since the last server frame. When enabled, bandwidth usage is estimated.
         * @env NETWORK_OBJECT_BATCH_USE_ESTIMATED_BANDWIDTH
         */
        networkObjectBatchUseEstimatedBandwidth?: boolean
        /**
         * When enabled, the bandwidth limit is a factor of the maximum bandwidth that can be sent. When disabled, the bandwidth limit is a hard limit.
         * @env NETWORK_OBJECT_BATCH_USE_DYNAMIC_MAXIMUM_BANDWIDTH
         */
        networkObjectBatchUseDynamicMaximumBandwidth?: boolean
        /**
         * The actual limit, could be a [0,1] value or a [1,inf] value depending on networkObjectBatchUseDynamicMaximumBandwidth. See above.
         * @env NETWORK_OBJECT_BATCH_BANDWIDTH_LIMIT
         */
        networkObjectBatchBandwidthLimit?: number
        /**
         * Number of objects in the create/destroy lists that are checked in a single server frame
         * @env NETWORK_OBJECT_BATCH_COMPUTE
         */
        networkObjectBatchCompute?: number
        /**
         * Maximum number of objects that can be sent for creation
         * @env NETWORK_OBJECT_BATCH_SEND_CREATE
         */
        networkObjectBatchSendCreate?: number
        /**
         * Maximum number of objects that can be sent for deletion
         * @env NETWORK_OBJECT_BATCH_SEND_DELETE
         */
        networkObjectBatchSendDelete?: number
        /**
         * highest terrain render distance on server (if higher than "viewDistance=" in DayZ client profile, client-side parameter applies)
         * @env DEFAULT_VISIBILITY
         */
        defaultVisibility?: number
        /**
         * highest object render distance on server (if higher than "preferredObjectViewDistance=" in DayZ client profile, client-side parameter applies)
         * @env DEFAULT_OBJECT_VIEW_DISTANCE
         */
        defaultObjectViewDistance?: number
        /**
         * 0 for brighter night, 1 for darker night, 2 for Sakhal-specific lighting - if enableCfgGameplayFile is enabled, this option will be overridden by the WorldsData::lightingConfig value
         * @env LIGHTING_CONFIG
         */
        lightingConfig?: number
        /**
         * Disables personal light for all clients connected to the server.
         * @env DISABLE_PERSONAL_LIGHT
         */
        disablePersonalLight?: boolean
        /**
         * When enabled, disables damage and destruction of fences and watchtowers.
         * @env DISABLE_BASE_DAMAGE
         */
        disableBaseDamage?: boolean
        /**
         * When enabled, disables damage and destruction of tents, barrels, wooden crates, and sea chests.
         * @env DISABLE_CONTAINER_DAMAGE
         */
        disableContainerDamage?: boolean
        /**
         * When enabled, disables the respawn dialog; new characters spawn randomly.
         * @env DISABLE_RESPAWN_DIALOG
         */
        disableRespawnDialog?: boolean
        /**
         * set to define the ping value from which the initial yellow ping warning is triggered (value in milliseconds)
         * @env PING_WARNING
         */
        pingWarning?: number
        /**
         * set to define the ping value from which the red ping warning is triggered (value in milliseconds)
         * @env PING_CRITICAL
         */
        pingCritical?: number
        /**
         * set to define the ping value from which a player is kicked from the server (value in milliseconds)
         * @env MAX_PING
         */
        maxPing?: number
        /**
         * set to define the server fps value under which the initial server fps warning is triggered (minimum value is 11)
         * @env SERVER_FPS_WARNING
         */
        serverFpsWarning?: number
        /**
         * Enables shot validation.
         * @env SHOT_VALIDATION
         */
        shotValidation?: boolean
        /**
         * forces the port the clients connect with
         * @env CLIENT_PORT
         */
        clientPort?: number
        /**
         * Enable support for the cfggameplay.json file.
         * @env ENABLE_CFG_GAMEPLAY_FILE
         */
        enableCfgGameplayFile?: boolean
        /**
         * Mission to load on server startup. <MissionName>.<TerrainName>
         * @default "dayzOffline.chernarusplus"
         * @env TEMPLATE
         */
        template: string
    }
    battleye: {
        /**
         * BattlEye/RCon bind IP written to `beserver_x64.cfg`. Leave unset to let BattlEye use its default behavior.
         * @env BE_IP
         */
        ip?: string
        /**
         * BattlEye/RCon port written to `beserver_x64.cfg`. If unset, BattlEye uses its built-in default port behavior.
         * @env BE_PORT
         */
        port?: string
        /**
         * Sets the password for the connection of the RCon tool (remote connection admin tool like BEC/Dart)
         * @env BE_PASSWORD
         */
        password?: string
    }
    steam: {
        /**
         * Steam API adapter. `local` uses the embedded depot client; `remote` delegates Steam downloads to a depot-daemon instance.
         * @default "local"
         * @env STEAM_API_ADAPTER
         */
        steamApiAdapter: "local" | "remote"
        /**
         * The username for the Steam account to use for downloading the server and mods. User/password login is supported but discouraged; prefer QR code login & cached credentials.
         * @env STEAM_USERNAME
         */
        steamUsername?: string
        /**
         * The password for the Steam account to use for downloading the server and mods. Discouraged except for bootstrapping credentials.
         * @env STEAM_PASSWORD
         */
        steamPassword?: string
        /**
         * The Steam Guard code/token for bootstrapping a Steam login when required.
         * @env STEAM_GUARD_CODE
         */
        steamGuardCode?: string
        /**
         * The Steam App ID for DayZ Server
         * @env STEAM_APP_ID
         */
        appID: number
        /**
         * The directory where the server is installed. This should be bind-mounted to a persistent directory on the host.
         * @env STEAM_DOWNLOAD_DIRECTORY
         */
        downloadDirectory: string
        /**
         * The directory where the Steam configuration is stored. Defaults to the value of `/root/.steam`.
         * @default "/root/.steam"
         * @env STEAM_CONFIG_DIRECTORY
         */
        configDirectory: string
        /**
         * Remote depot-daemon transport. Options: `uds`.
         * @default "uds"
         * @env STEAM_CONTENT_TRANSPORT
         */
        steamContentTransport: "uds" | "tcp"
        /**
         * Unix socket path for depot-daemon when `STEAM_API_ADAPTER=remote` and `STEAM_CONTENT_TRANSPORT=uds`.
         * @default "/root/.steam/depot.sock"
         * @env STEAM_CONTENT_SOCKET
         */
        steamContentSocket: string
        /**
         * Remote depot-daemon URL. For UDS, this is a fake origin routed through Bun's Unix-socket fetch support.
         * @default "http://depot-daemon.local"
         * @env STEAM_CONTENT_URL
         */
        steamContentUrl: string
        /**
         * Socket.IO path exposed by depot-daemon.
         * @default "/socket.io/"
         * @env STEAM_CONTENT_SOCKET_IO_PATH
         */
        steamContentSocketIoPath: string
        /**
         * Remote depot-daemon connection and request timeout in milliseconds.
         * @default 60000
         * @env STEAM_CONTENT_TIMEOUT_MS
         */
        steamContentTimeoutMs: number
        /**
         * Consumer identity used when registering live content locks with depot-daemon. Defaults to a ServerZ/container/app identifier.
         * @env STEAM_CONTENT_CONSUMER_ID
         */
        steamContentConsumerId?: string
        /**
         * Interval for refreshing remote depot-daemon content locks while DayZ is running.
         * @default 10000
         * @env STEAM_CONTENT_LOCK_HEARTBEAT_MS
         */
        steamContentLockHeartbeatMs: number
        /**
         * Depot-daemon content-lock TTL. If heartbeats stop for this long, daemon releases this consumer's locks.
         * @default 30000
         * @env STEAM_CONTENT_LOCK_TTL_MS
         */
        steamContentLockTtlMs: number
        /**
         * Remote depot-daemon validation failure policy when content repair is suppressed by active content locks. `warn` logs and continues startup; `fail` aborts startup.
         * @default "warn"
         * @env STEAM_REMOTE_VALIDATION_FAILURE
         */
        steamRemoteValidationFailure: "warn" | "fail"
        /**
         * Echo minor remote Steam details to the console, when connected to depot-daemon.
         * @env ECHO_MINOR_REMOTE_STEAM_DETAILS
         */
        echoMinorRemoteSteamDetails?: boolean
        /**
         * Download profile for Steam app/server files
         * @default "fast"
         * @env STEAM_APP_DOWNLOAD_PROFILE
         */
        appDownloadProfile: "safe" | "medium" | "fast"
        /**
         * Download profile for Steam workshop items
         * @default "fast"
         * @env STEAM_WORKSHOP_DOWNLOAD_PROFILE
         */
        workshopDownloadProfile: "safe" | "medium" | "fast"
        /**
         * Default branch/beta name. Clients may override this per request.
         * @default "public"
         * @env STEAM_BRANCH
         */
        branch: string
        /**
         * Default password for protected branches. Clients may override this per request.
         * @env STEAM_BRANCH_PASSWORD
         */
        branchPassword?: string
        /**
         * Platform filter passed to depot resolution.
         * @env STEAM_OS
         */
        os?: string
        /**
         * Architecture filter passed to depot resolution.
         * @env STEAM_ARCH
         */
        arch?: string
        /**
         * Language filter passed to depot resolution.
         * @default "english"
         * @env STEAM_LANGUAGE
         */
        language: string
        /**
         * Include child/dependency workshop items.
         * @default true
         * @env STEAM_WORKSHOP_INCLUDE_CHILDREN
         */
        workshopIncludeChildren: boolean
        /**
         * Keep each workshop item in a separate directory.
         * @default true
         * @env STEAM_WORKSHOP_SEPARATE_ITEM_DIRS
         */
        workshopSeparateItemDirectories: boolean
        /**
         * Behavior when workshop dependencies contain cycles.
         * @default "skip"
         * @env STEAM_WORKSHOP_CYCLE_MODE
         */
        workshopCycleMode: "skip" | "throw"
        /**
         * Connection protocol used by steam-user for Steam CM logon. `auto` currently prefers TCP under Bun; use `websocket` when outbound Steam CM TCP is blocked.
         * @default "auto"
         * @env STEAM_USER_CONNECTION_PROTOCOL
         */
        steamUserConnectionProtocol: "auto" | "tcp" | "websocket"
        /**
         * Download backend. `bun-cdn` is the native fast path.
         * @default "bun-cdn"
         * @env STEAM_DOWNLOAD_BACKEND
         */
        downloadBackend: "bun-cdn" | "managed-chunks" | "steam-user-file"
        /**
         * Max concurrent chunks per depot for `bun-cdn`/`managed-chunks`.
         * @default 32
         * @env STEAM_MAX_CONCURRENT_CHUNKS
         */
        maxConcurrentChunks: number
        /**
         * Max depots processed concurrently.
         * @default 3
         * @env STEAM_MAX_CONCURRENT_DEPOTS
         */
        maxConcurrentDepots: number
        /**
         * Max files for `steam-user-file` backend; less relevant for `bun-cdn`.
         * @default 6
         * @env STEAM_MAX_CONCURRENT_FILES
         */
        maxConcurrentFiles: number
        /**
         * Max simultaneously open output file handles for managed chunk writing.
         * @default 64
         * @env STEAM_MAX_OPEN_FILE_HANDLES
         */
        maxOpenFileHandles: number
        /**
         * Per-attempt CDN fetch timeout for `bun-cdn`.
         * @default 15000
         * @env STEAM_BUN_CDN_FETCH_TIMEOUT_MS
         */
        bunCdnFetchTimeoutMs: number
        /**
         * Fall back to `steam-user.downloadChunk()` when the native CDN chunk path fails.
         * @env STEAM_BUN_CDN_FALLBACK
         */
        bunCdnFallbackToSteamUser: boolean
        /**
         * Minimum interval between emitted progress events from the depot client.
         * @default 500
         * @env STEAM_PROGRESS_INTERVAL_MS
         */
        progressIntervalMs: number
        /**
         * Minimum interval between depot-daemon progress log lines.
         * @default 1000
         * @env STEAM_PROGRESS_PRINT_INTERVAL_MS
         */
        progressPrintIntervalMs: number
        /**
         * Verification policy for freshly downloaded files/chunks. `full-file` is safest; `chunks-only` avoids final full-file reads.
         * @default "full-file"
         * @env STEAM_VERIFY_DOWNLOADED
         */
        verifyDownloaded: "full-file" | "chunks-only" | "none"
        /**
         * Hash existing matching files before skipping.
         * @default true
         * @env STEAM_VERIFY_EXISTING
         */
        verifyExisting?: boolean
        /**
         * Redownload missing/corrupt files found by validation.
         * @default true
         * @env STEAM_REPAIR_INVALID_FILES
         */
        repairInvalidFiles?: boolean
        /**
         * Number of repair passes after validation failure.
         * @default 1
         * @env STEAM_MAX_VALIDATION_REPAIR_ATTEMPTS
         */
        maxValidationRepairAttempts: number
        /**
         * Validation-only file concurrency.
         * @default 8
         * @env STEAM_VALIDATE_CONCURRENT_FILES
         */
        validateConcurrentFiles: number
        /**
         * Validation-only hash checking.
         * @default true
         * @env STEAM_VALIDATE_HASHES
         */
        validateHashes: boolean
        /**
         * Compression strategy for `bun-cdn`.
         * @default "auto"
         * @env STEAM_CDN_COMPRESSION
         */
        bunCdnCompression: "auto" | "steam-user"
        /**
         * Zstd backend for VSZa chunks.
         * @default "auto"
         * @env STEAM_CDN_ZSTD_BACKEND
         */
        bunCdnZstdBackend: "auto" | "zstddec" | "mongodb-zstd" | "steam-user"
        /**
         * LZMA/VZip backend. `auto` prefers process-isolated ffi-liblzma under Bun when available.
         * @default "auto"
         * @env STEAM_CDN_LZMA_BACKEND
         */
        bunCdnLzmaBackend: "auto" | "ffi-liblzma" | "ffi-liblzma-process" | "ffi-liblzma-worker" | "zig-wasm" | "lzma-native" | "lzma" | "steam-user"
        /**
         * Bun executable used by process-isolated ffi-liblzma workers, especially when main process is not Bun.
         * @env STEAM_BUN_EXECUTABLE
         */
        bunExecutable?: string
        /**
         * Process/worker count for ffi-liblzma decompression.
         * @env STEAM_FFI_LZMA_WORKERS
         */
        ffiLzmaWorkers?: number
        /**
         * Retry count for process-isolated ffi-liblzma jobs after worker crashes.
         * @default 2
         * @env STEAM_FFI_LZMA_PROCESS_RETRIES
         */
        ffiLzmaProcessRetries: number
        /**
         * Explicit path to `libsteam_lzma`.
         * @env STEAM_FFI_LZMA_LIBRARY_PATH
         */
        ffiLzmaLibraryPath?: string
        /**
         * liblzma memory limit. Raise if VZip decompression reports memory-limit failures.
         * @env STEAM_FFI_LZMA_MEMLIMIT_BYTES
         */
        ffiLzmaMemlimitBytes?: number
        /**
         * Node executable used by the Node/lzma-native worker backend. Mostly irrelevant under Bun unless that backend is selected.
         * @default "node"
         * @env STEAM_NODE_EXECUTABLE
         */
        nodeExecutable: string
        /**
         * Require path used inside Node lzma-native workers. Internal/advanced.
         * @default "lzma-native"
         * @env STEAM_LZMA_NATIVE_REQUIRE_PATH
         */
        lzmaNativeRequirePath: string
    }
    _defaults: Partial<Omit<ServerZGeneratedConfig, "_defaults">>
}
